# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlgoritmoPRESENT.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AlgoritmoPRESENT(object):
    def setupUi(self, AlgoritmoPRESENT):
        AlgoritmoPRESENT.setObjectName("AlgoritmoPRESENT")
        AlgoritmoPRESENT.resize(951, 703)
        self.centralwidget = QtWidgets.QWidget(AlgoritmoPRESENT)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setObjectName("tabWidget")
        self.AlgoritmoPRESENT1 = QtWidgets.QWidget()
        self.AlgoritmoPRESENT1.setObjectName("AlgoritmoPRESENT1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.AlgoritmoPRESENT1)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_3 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_3.setObjectName("label_3")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 260, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.textoclaro = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.textoclaro.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textoclaro.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textoclaro.setAcceptDrops(True)
        self.textoclaro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textoclaro.setAutoFillBackground(False)
        self.textoclaro.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.textoclaro.setFrame(True)
        self.textoclaro.setAlignment(QtCore.Qt.AlignCenter)
        self.textoclaro.setReadOnly(True)
        self.textoclaro.setObjectName("textoclaro")
        self.horizontalLayout.addWidget(self.textoclaro)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setContentsMargins(0, 10, -1, 0)
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_43 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_43.setObjectName("label_43")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.ronda = QtWidgets.QSpinBox(self.AlgoritmoPRESENT1)
        self.ronda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ronda.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ronda.setAlignment(QtCore.Qt.AlignCenter)
        self.ronda.setReadOnly(True)
        self.ronda.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ronda.setMinimum(1)
        self.ronda.setMaximum(31)
        self.ronda.setProperty("value", 1)
        self.ronda.setObjectName("ronda")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ronda)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.formLayout_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(0, 10, 0, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_44 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_44.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_44)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 13, 0, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 280, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_48 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_5.addWidget(self.label_48)
        self.state = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.state.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setDragEnabled(False)
        self.state.setReadOnly(True)
        self.state.setObjectName("state")
        self.horizontalLayout_5.addWidget(self.state)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_6 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 280, -1)
        self.horizontalLayout_6.setSpacing(28)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_50 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_6.addWidget(self.label_50)
        self.claveronda = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        font = QtGui.QFont()
        font.setItalic(True)
        self.claveronda.setFont(font)
        self.claveronda.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.claveronda.setFrame(True)
        self.claveronda.setAlignment(QtCore.Qt.AlignCenter)
        self.claveronda.setReadOnly(True)
        self.claveronda.setObjectName("claveronda")
        self.horizontalLayout_6.addWidget(self.claveronda)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)
        self.botonxor = QtWidgets.QPushButton(self.AlgoritmoPRESENT1)
        self.botonxor.setEnabled(True)
        self.botonxor.setObjectName("botonxor")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.botonxor)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 5, 280, -1)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_51 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_8.addWidget(self.label_51)
        self.resultadoxor = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.resultadoxor.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.resultadoxor.setText("")
        self.resultadoxor.setAlignment(QtCore.Qt.AlignCenter)
        self.resultadoxor.setReadOnly(True)
        self.resultadoxor.setObjectName("resultadoxor")
        self.horizontalLayout_8.addWidget(self.resultadoxor)
        self.formLayout_4.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.formLayout_3.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setContentsMargins(0, 20, -1, -1)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_61 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_61.setObjectName("label_61")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_61)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 5, 20, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_52 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_15.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_15.addWidget(self.label_53)
        self.trozo15 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo15.setText("")
        self.trozo15.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo15.setReadOnly(True)
        self.trozo15.setObjectName("trozo15")
        self.horizontalLayout_15.addWidget(self.trozo15)
        self.label_54 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_15.addWidget(self.label_54)
        self.trozo14 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo14.setText("")
        self.trozo14.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo14.setReadOnly(True)
        self.trozo14.setObjectName("trozo14")
        self.horizontalLayout_15.addWidget(self.trozo14)
        self.label_55 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_15.addWidget(self.label_55)
        self.trozo13 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo13.setText("")
        self.trozo13.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo13.setReadOnly(True)
        self.trozo13.setObjectName("trozo13")
        self.horizontalLayout_15.addWidget(self.trozo13)
        self.label_56 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_15.addWidget(self.label_56)
        self.trozo12 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo12.setText("")
        self.trozo12.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo12.setReadOnly(True)
        self.trozo12.setObjectName("trozo12")
        self.horizontalLayout_15.addWidget(self.trozo12)
        self.label_57 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_15.addWidget(self.label_57)
        self.trozo11 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo11.setText("")
        self.trozo11.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo11.setReadOnly(True)
        self.trozo11.setObjectName("trozo11")
        self.horizontalLayout_15.addWidget(self.trozo11)
        self.label_58 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_15.addWidget(self.label_58)
        self.trozo10 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo10.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.trozo10.setText("")
        self.trozo10.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo10.setReadOnly(True)
        self.trozo10.setObjectName("trozo10")
        self.horizontalLayout_15.addWidget(self.trozo10)
        self.label_59 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_15.addWidget(self.label_59)
        self.trozo9 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo9.setText("")
        self.trozo9.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo9.setReadOnly(True)
        self.trozo9.setObjectName("trozo9")
        self.horizontalLayout_15.addWidget(self.trozo9)
        self.label_60 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_15.addWidget(self.label_60)
        self.trozo8 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo8.setText("")
        self.trozo8.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo8.setObjectName("trozo8")
        self.horizontalLayout_15.addWidget(self.trozo8)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_15)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.botonTrozear = QtWidgets.QPushButton(self.AlgoritmoPRESENT1)
        self.botonTrozear.setEnabled(False)
        self.botonTrozear.setObjectName("botonTrozear")
        self.horizontalLayout_11.addWidget(self.botonTrozear)
        self.botontransformar = QtWidgets.QPushButton(self.AlgoritmoPRESENT1)
        self.botontransformar.setEnabled(False)
        self.botontransformar.setObjectName("botontransformar")
        self.horizontalLayout_11.addWidget(self.botontransformar)
        self.verSBoxPRES = QtWidgets.QPushButton(self.AlgoritmoPRESENT1)
        self.verSBoxPRES.setObjectName("verSBoxPRES")
        self.horizontalLayout_11.addWidget(self.verSBoxPRES)
        self.formLayout_5.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 5, 20, 5)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_62 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_16.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_16.addWidget(self.label_63)
        self.trozo7 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo7.setText("")
        self.trozo7.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo7.setReadOnly(True)
        self.trozo7.setObjectName("trozo7")
        self.horizontalLayout_16.addWidget(self.trozo7)
        self.label_64 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_16.addWidget(self.label_64)
        self.trozo6 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo6.setText("")
        self.trozo6.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo6.setReadOnly(True)
        self.trozo6.setObjectName("trozo6")
        self.horizontalLayout_16.addWidget(self.trozo6)
        self.label_65 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_16.addWidget(self.label_65)
        self.trozo5 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo5.setText("")
        self.trozo5.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo5.setReadOnly(True)
        self.trozo5.setObjectName("trozo5")
        self.horizontalLayout_16.addWidget(self.trozo5)
        self.label_66 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_16.addWidget(self.label_66)
        self.trozo4 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo4.setText("")
        self.trozo4.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo4.setReadOnly(True)
        self.trozo4.setObjectName("trozo4")
        self.horizontalLayout_16.addWidget(self.trozo4)
        self.label_67 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_16.addWidget(self.label_67)
        self.trozo3 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo3.setText("")
        self.trozo3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo3.setReadOnly(True)
        self.trozo3.setObjectName("trozo3")
        self.horizontalLayout_16.addWidget(self.trozo3)
        self.label_68 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_16.addWidget(self.label_68)
        self.trozo2 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo2.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.trozo2.setText("")
        self.trozo2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo2.setReadOnly(False)
        self.trozo2.setObjectName("trozo2")
        self.horizontalLayout_16.addWidget(self.trozo2)
        self.label_69 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_16.addWidget(self.label_69)
        self.trozo1 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo1.setText("")
        self.trozo1.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo1.setReadOnly(True)
        self.trozo1.setObjectName("trozo1")
        self.horizontalLayout_16.addWidget(self.trozo1)
        self.label_70 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_16.addWidget(self.label_70)
        self.trozo0 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.trozo0.setText("")
        self.trozo0.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo0.setObjectName("trozo0")
        self.horizontalLayout_16.addWidget(self.trozo0)
        self.formLayout_5.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_16)
        self.formLayout_3.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.formLayout_5)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(0, 20, -1, -1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_71 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_71.setObjectName("label_71")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_71)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 5, 280, 5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_81 = QtWidgets.QLabel(self.AlgoritmoPRESENT1)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_18.addWidget(self.label_81)
        self.statePaso2 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT1)
        self.statePaso2.setText("")
        self.statePaso2.setAlignment(QtCore.Qt.AlignCenter)
        self.statePaso2.setReadOnly(True)
        self.statePaso2.setObjectName("statePaso2")
        self.horizontalLayout_18.addWidget(self.statePaso2)
        self.formLayout_6.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_18)
        self.formLayout_3.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.formLayout_6)
        self.tabWidget.addTab(self.AlgoritmoPRESENT1, "")
        self.AlgoritmoPRESENT2 = QtWidgets.QWidget()
        self.AlgoritmoPRESENT2.setObjectName("AlgoritmoPRESENT2")
        self.formLayout_10 = QtWidgets.QFormLayout(self.AlgoritmoPRESENT2)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_5 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_5.setObjectName("label_5")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setContentsMargins(0, 20, -1, -1)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_72 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_72.setObjectName("label_72")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_72)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 5, 264, -1)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_83 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_83.setObjectName("label_83")
        self.horizontalLayout_9.addWidget(self.label_83)
        self.statePaso2_1 = QtWidgets.QLineEdit(self.AlgoritmoPRESENT2)
        self.statePaso2_1.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.statePaso2_1.setText("")
        self.statePaso2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.statePaso2_1.setReadOnly(True)
        self.statePaso2_1.setObjectName("statePaso2_1")
        self.horizontalLayout_9.addWidget(self.statePaso2_1)
        self.formLayout_7.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_9)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.botonPermutar = QtWidgets.QPushButton(self.AlgoritmoPRESENT2)
        self.botonPermutar.setEnabled(False)
        self.botonPermutar.setObjectName("botonPermutar")
        self.horizontalLayout_12.addWidget(self.botonPermutar)
        self.botonVerPBoxPRES = QtWidgets.QPushButton(self.AlgoritmoPRESENT2)
        self.botonVerPBoxPRES.setObjectName("botonVerPBoxPRES")
        self.horizontalLayout_12.addWidget(self.botonVerPBoxPRES)
        self.formLayout_7.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, 5, 264, -1)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_84 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_84.setObjectName("label_84")
        self.horizontalLayout_10.addWidget(self.label_84)
        self.resultadoPermutacion = QtWidgets.QLineEdit(self.AlgoritmoPRESENT2)
        self.resultadoPermutacion.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.resultadoPermutacion.setText("")
        self.resultadoPermutacion.setAlignment(QtCore.Qt.AlignCenter)
        self.resultadoPermutacion.setReadOnly(True)
        self.resultadoPermutacion.setObjectName("resultadoPermutacion")
        self.horizontalLayout_10.addWidget(self.resultadoPermutacion)
        self.formLayout_7.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_10)
        self.formLayout_10.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.formLayout_7)
        self.botonNuevaRonda = QtWidgets.QPushButton(self.AlgoritmoPRESENT2)
        self.botonNuevaRonda.setEnabled(False)
        self.botonNuevaRonda.setObjectName("botonNuevaRonda")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.botonNuevaRonda)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setContentsMargins(0, 50, 0, -1)
        self.formLayout_8.setObjectName("formLayout_8")
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setContentsMargins(-1, 21, -1, -1)
        self.formLayout_9.setHorizontalSpacing(0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_45 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_45.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_45)
        self.formLayout_8.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.formLayout_9)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 13, 0, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(65, -1, 219, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_49 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_7.addWidget(self.label_49)
        self.stateadicionclave = QtWidgets.QLineEdit(self.AlgoritmoPRESENT2)
        self.stateadicionclave.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.stateadicionclave.setAlignment(QtCore.Qt.AlignCenter)
        self.stateadicionclave.setDragEnabled(False)
        self.stateadicionclave.setReadOnly(True)
        self.stateadicionclave.setObjectName("stateadicionclave")
        self.horizontalLayout_7.addWidget(self.stateadicionclave)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.label_7 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(0, -1, 219, -1)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_73 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_13.addWidget(self.label_73)
        self.clavepostblanq = QtWidgets.QLineEdit(self.AlgoritmoPRESENT2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.clavepostblanq.setFont(font)
        self.clavepostblanq.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.clavepostblanq.setFrame(True)
        self.clavepostblanq.setAlignment(QtCore.Qt.AlignCenter)
        self.clavepostblanq.setReadOnly(True)
        self.clavepostblanq.setObjectName("clavepostblanq")
        self.horizontalLayout_13.addWidget(self.clavepostblanq)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.formLayout_8.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_2)
        self.botonxor_2 = QtWidgets.QPushButton(self.AlgoritmoPRESENT2)
        self.botonxor_2.setEnabled(True)
        self.botonxor_2.setObjectName("botonxor_2")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.botonxor_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, 5, 209, -1)
        self.horizontalLayout_14.setSpacing(6)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_74 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_14.addWidget(self.label_74)
        self.resultadoxoradicional = QtWidgets.QLineEdit(self.AlgoritmoPRESENT2)
        self.resultadoxoradicional.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.resultadoxoradicional.setText("")
        self.resultadoxoradicional.setAlignment(QtCore.Qt.AlignCenter)
        self.resultadoxoradicional.setReadOnly(True)
        self.resultadoxoradicional.setObjectName("resultadoxoradicional")
        self.horizontalLayout_14.addWidget(self.resultadoxoradicional)
        self.botonhex = QtWidgets.QPushButton(self.AlgoritmoPRESENT2)
        self.botonhex.setEnabled(False)
        self.botonhex.setObjectName("botonhex")
        self.horizontalLayout_14.addWidget(self.botonhex)
        self.formLayout_8.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_14)
        self.label_8 = QtWidgets.QLabel(self.AlgoritmoPRESENT2)
        self.label_8.setObjectName("label_8")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.formLayout_10.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.formLayout_8)
        self.tabWidget.addTab(self.AlgoritmoPRESENT2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        AlgoritmoPRESENT.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AlgoritmoPRESENT)
        self.statusbar.setObjectName("statusbar")
        AlgoritmoPRESENT.setStatusBar(self.statusbar)

        self.retranslateUi(AlgoritmoPRESENT)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AlgoritmoPRESENT)

    def retranslateUi(self, AlgoritmoPRESENT):
        _translate = QtCore.QCoreApplication.translate
        AlgoritmoPRESENT.setWindowTitle(_translate("AlgoritmoPRESENT", "Algoritmo PRESENT"))
        self.label_3.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-weight:600;\">Algoritmo PRESENT</span></p></body></html>"))
        self.label.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Nota</span>: Cifraremos el bloque 0 del ejemplo.</p></body></html>"))
        self.label_2.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>Bloque 0: </p></body></html>"))
        self.textoclaro.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p>Bloque a cifrar</p></body></html>"))
        self.textoclaro.setText(_translate("AlgoritmoPRESENT", "0100010101101110001000000111010101101110001000000110110001110101"))
        self.label_43.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>Ronda </p></body></html>"))
        self.label_4.setText(_translate("AlgoritmoPRESENT", "i= Número de ronda"))
        self.label_44.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-weight:600;\">1. Adición de clave.</span> El nuevo estado (state<span style=\" vertical-align:sub;\">i</span>) será el resultado de una operación XOR entre el estado actual (state) y la clave de ronda i </p></body></html>"))
        self.label_48.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i</span>: </p></body></html>"))
        self.state.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-style:normal;\">Estado actual (64 bits)</span></p></body></html>"))
        self.state.setText(_translate("AlgoritmoPRESENT", "0100010101101110001000000111010101101110001000000110110001110101"))
        self.label_6.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:16pt;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⊕</span></p></body></html>"))
        self.label_50.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>K<span style=\" vertical-align:sub;\">i</span>:</p></body></html>"))
        self.claveronda.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-style:normal;\">clave de ronda de 64 bits</span></p></body></html>"))
        self.claveronda.setText(_translate("AlgoritmoPRESENT", "0110001101101001011001100101000001010010010001010101001101000101"))
        self.botonxor.setText(_translate("AlgoritmoPRESENT", "XOR"))
        self.label_51.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i </span>= </p></body></html>"))
        self.resultadoxor.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-style:normal;\">Nuevo state</span><span style=\" font-style:normal; vertical-align:super;\">i</span></p></body></html>"))
        self.label_61.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-weight:600;\">2. Capa de sustitución.</span> Se trozea state<span style=\" vertical-align:sub;\">i </span>en 16 trozos. Cada trozo pasa por la SBox (caja de sustitución) y se obtienen nuevos valores.</p></body></html>"))
        self.label_52.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>Trozos: </p></body></html>"))
        self.label_53.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">15</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_54.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">14</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_55.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">13</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_56.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">12</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_57.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">11</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_58.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">10</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_59.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">09</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_60.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">08</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.botonTrozear.setText(_translate("AlgoritmoPRESENT", "Trozear"))
        self.botontransformar.setText(_translate("AlgoritmoPRESENT", "Transformar por SBox"))
        self.verSBoxPRES.setText(_translate("AlgoritmoPRESENT", "Ver SBox"))
        self.label_62.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>Trozos: </p></body></html>"))
        self.label_63.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">07</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_64.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">06</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_65.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">05</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_66.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">04</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_67.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">03</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_68.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">02</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_69.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">01</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_70.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:12pt;\">w</span><span style=\" font-size:12pt; vertical-align:sub;\">00</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_71.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>Se obtiene el nuevo state<span style=\" vertical-align:super;\">i </span>anidando los trozos (w<span style=\" vertical-align:sub;\">15</span>...w<span style=\" vertical-align:sub;\">0</span>).</p></body></html>"))
        self.label_81.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i</span>:</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AlgoritmoPRESENT1), _translate("AlgoritmoPRESENT", "Algoritmo PRESENT (1)"))
        self.label_5.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-weight:600;\">Algoritmo PRESENT</span></p></body></html>"))
        self.label_72.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-weight:600;\">3. Capa de permutación.</span> Cada bit del state<span style=\" vertical-align:super;\">i </span>(obtenido en el paso 2) es movido a una nueva posición, según la PBox(caja de permutación).</p></body></html>"))
        self.label_83.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i </span>= </p></body></html>"))
        self.statePaso2_1.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-style:normal;\">Nuevo state</span><span style=\" font-style:normal; vertical-align:super;\">i</span></p></body></html>"))
        self.botonPermutar.setText(_translate("AlgoritmoPRESENT", "Permutar"))
        self.botonVerPBoxPRES.setText(_translate("AlgoritmoPRESENT", "Ver PBox"))
        self.label_84.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i </span>= </p></body></html>"))
        self.resultadoPermutacion.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-style:normal;\">Nuevo state</span><span style=\" font-style:normal; vertical-align:super;\">i</span></p></body></html>"))
        self.botonNuevaRonda.setText(_translate("AlgoritmoPRESENT", "Nueva Ronda"))
        self.label_45.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-weight:600;\">Adición de clave.</span> El estado final (state<span style=\" vertical-align:sub;\">i</span>), que será el bloque 0 cifrado, es el resultado de una operación XOR entre el state<span style=\" vertical-align:super;\">i </span> del paso 3<br/>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; y la clave adicional de post blanqueamiento </p></body></html>\n"
""))
        self.label_49.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>state<span style=\" vertical-align:super;\">31</span>: </p></body></html>"))
        self.stateadicionclave.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-style:normal;\">Estado actual (64 bits)</span></p></body></html>"))
        self.stateadicionclave.setText(_translate("AlgoritmoPRESENT", "1011000001110100000111111010100001110000001010101010000010111100"))
        self.label_7.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-size:16pt;\">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;⊕</span></p></body></html>"))
        self.label_73.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>K<span style=\" vertical-align:sub;\">post-blanqueamiento</span>:</p></body></html>"))
        self.clavepostblanq.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-style:normal;\">clave de ronda de 64 bits</span></p></body></html>"))
        self.clavepostblanq.setText(_translate("AlgoritmoPRESENT", "0101101110110011011000101100101111110110101101111100000111111100"))
        self.botonxor_2.setText(_translate("AlgoritmoPRESENT", "XOR"))
        self.label_74.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>bloque cifrado = </p></body></html>"))
        self.resultadoxoradicional.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p><span style=\" font-style:normal;\">Nuevo state</span><span style=\" font-style:normal; vertical-align:super;\">i</span></p></body></html>"))
        self.botonhex.setToolTip(_translate("AlgoritmoPRESENT", "<html><head/><body><p>Convertir a hexadecimal</p></body></html>"))
        self.botonhex.setText(_translate("AlgoritmoPRESENT", "Hexadecimal"))
        self.label_8.setText(_translate("AlgoritmoPRESENT", "<html><head/><body><p>Una vez acabadas las 31 rondas, se realiza el siguiente <span style=\" font-weight:600;\">paso adicional</span>: </p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AlgoritmoPRESENT2), _translate("AlgoritmoPRESENT", "Algoritmo PRESENT (2)"))

