# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlgoritmoMIBS.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AlgoritmoMIBS(object):
    def setupUi(self, AlgoritmoMIBS):
        AlgoritmoMIBS.setObjectName("AlgoritmoMIBS")
        AlgoritmoMIBS.setWindowModality(QtCore.Qt.NonModal)
        AlgoritmoMIBS.setEnabled(True)
        AlgoritmoMIBS.resize(911, 760)
        AlgoritmoMIBS.setLayoutDirection(QtCore.Qt.LeftToRight)
        AlgoritmoMIBS.setTabPosition(QtWidgets.QTabWidget.South)
        AlgoritmoMIBS.setDocumentMode(False)
        self.AlgoritmoMIBS1 = QtWidgets.QWidget()
        self.AlgoritmoMIBS1.setObjectName("AlgoritmoMIBS1")
        self.formLayout_11 = QtWidgets.QFormLayout(self.AlgoritmoMIBS1)
        self.formLayout_11.setContentsMargins(0, 0, 0, 0)
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_3 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_3.setObjectName("label_3")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setContentsMargins(20, 10, -1, 0)
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_43 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_43.setObjectName("label_43")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.ronda = QtWidgets.QSpinBox(self.AlgoritmoMIBS1)
        self.ronda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ronda.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ronda.setAlignment(QtCore.Qt.AlignCenter)
        self.ronda.setReadOnly(True)
        self.ronda.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ronda.setMinimum(0)
        self.ronda.setMaximum(32)
        self.ronda.setProperty("value", 0)
        self.ronda.setObjectName("ronda")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ronda)
        self.formLayout_11.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.formLayout_12)
        self.label_47 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_47.setObjectName("label_47")
        self.formLayout_11.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(20, 0, 0, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_17 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 6, 25, -1)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_23 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        self.leftinicial = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.leftinicial.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.leftinicial.setText("")
        self.leftinicial.setAlignment(QtCore.Qt.AlignCenter)
        self.leftinicial.setDragEnabled(False)
        self.leftinicial.setReadOnly(True)
        self.leftinicial.setObjectName("leftinicial")
        self.horizontalLayout.addWidget(self.leftinicial)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 6, 25, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_40 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_2.addWidget(self.label_40)
        self.rightinicial = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        font = QtGui.QFont()
        font.setItalic(True)
        self.rightinicial.setFont(font)
        self.rightinicial.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.rightinicial.setText("")
        self.rightinicial.setFrame(True)
        self.rightinicial.setAlignment(QtCore.Qt.AlignCenter)
        self.rightinicial.setReadOnly(True)
        self.rightinicial.setObjectName("rightinicial")
        self.horizontalLayout_2.addWidget(self.rightinicial)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.botondividir = QtWidgets.QPushButton(self.AlgoritmoMIBS1)
        self.botondividir.setObjectName("botondividir")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.botondividir)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_41 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_3.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_3.addWidget(self.label_42)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.formLayout_11.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(20, 10, 0, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_44 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_44.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_44)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout_2)
        self.botonxor = QtWidgets.QPushButton(self.AlgoritmoMIBS1)
        self.botonxor.setEnabled(False)
        self.botonxor.setObjectName("botonxor")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.botonxor)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 13, 0, -1)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 20, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_48 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_5.addWidget(self.label_48)
        self.left = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.left.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.left.setText("")
        self.left.setAlignment(QtCore.Qt.AlignCenter)
        self.left.setDragEnabled(False)
        self.left.setReadOnly(True)
        self.left.setObjectName("left")
        self.horizontalLayout_5.addWidget(self.left)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, 20, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_50 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_6.addWidget(self.label_50)
        self.claveronda = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        font = QtGui.QFont()
        font.setItalic(True)
        self.claveronda.setFont(font)
        self.claveronda.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.claveronda.setText("")
        self.claveronda.setFrame(True)
        self.claveronda.setAlignment(QtCore.Qt.AlignCenter)
        self.claveronda.setReadOnly(True)
        self.claveronda.setObjectName("claveronda")
        self.horizontalLayout_6.addWidget(self.claveronda)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 5, 457, -1)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_51 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_8.addWidget(self.label_51)
        self.resultadoxor = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.resultadoxor.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.resultadoxor.setText("")
        self.resultadoxor.setAlignment(QtCore.Qt.AlignCenter)
        self.resultadoxor.setReadOnly(True)
        self.resultadoxor.setObjectName("resultadoxor")
        self.horizontalLayout_8.addWidget(self.resultadoxor)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.formLayout_11.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setContentsMargins(20, 20, -1, -1)
        self.formLayout_5.setObjectName("formLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.botonTrozear = QtWidgets.QPushButton(self.AlgoritmoMIBS1)
        self.botonTrozear.setEnabled(False)
        self.botonTrozear.setObjectName("botonTrozear")
        self.horizontalLayout_11.addWidget(self.botonTrozear)
        self.botontransformar = QtWidgets.QPushButton(self.AlgoritmoMIBS1)
        self.botontransformar.setEnabled(False)
        self.botontransformar.setObjectName("botontransformar")
        self.horizontalLayout_11.addWidget(self.botontransformar)
        self.botonverSBox = QtWidgets.QPushButton(self.AlgoritmoMIBS1)
        self.botonverSBox.setObjectName("botonverSBox")
        self.horizontalLayout_11.addWidget(self.botonverSBox)
        self.formLayout_5.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_11)
        self.label_61 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_61.setObjectName("label_61")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_61)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 5, 20, 5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_52 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_15.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_15.addWidget(self.label_53)
        self.trozo8 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo8.setText("")
        self.trozo8.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo8.setObjectName("trozo8")
        self.horizontalLayout_15.addWidget(self.trozo8)
        self.label_54 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_15.addWidget(self.label_54)
        self.trozo7 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo7.setText("")
        self.trozo7.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo7.setObjectName("trozo7")
        self.horizontalLayout_15.addWidget(self.trozo7)
        self.label_55 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_15.addWidget(self.label_55)
        self.trozo6 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo6.setText("")
        self.trozo6.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo6.setObjectName("trozo6")
        self.horizontalLayout_15.addWidget(self.trozo6)
        self.label_56 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_15.addWidget(self.label_56)
        self.trozo5 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo5.setText("")
        self.trozo5.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo5.setObjectName("trozo5")
        self.horizontalLayout_15.addWidget(self.trozo5)
        self.label_57 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_15.addWidget(self.label_57)
        self.trozo4 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo4.setText("")
        self.trozo4.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo4.setObjectName("trozo4")
        self.horizontalLayout_15.addWidget(self.trozo4)
        self.label_58 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_15.addWidget(self.label_58)
        self.trozo3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo3.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.trozo3.setText("")
        self.trozo3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo3.setReadOnly(True)
        self.trozo3.setObjectName("trozo3")
        self.horizontalLayout_15.addWidget(self.trozo3)
        self.label_59 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_15.addWidget(self.label_59)
        self.trozo2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo2.setText("")
        self.trozo2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo2.setObjectName("trozo2")
        self.horizontalLayout_15.addWidget(self.trozo2)
        self.label_60 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_15.addWidget(self.label_60)
        self.trozo1 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo1.setText("")
        self.trozo1.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo1.setObjectName("trozo1")
        self.horizontalLayout_15.addWidget(self.trozo1)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_15)
        self.formLayout_11.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.formLayout_5)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setContentsMargins(20, 5, 330, 0)
        self.formLayout_3.setHorizontalSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.textoclaro = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.textoclaro.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.textoclaro.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.textoclaro.setAcceptDrops(True)
        self.textoclaro.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textoclaro.setAutoFillBackground(False)
        self.textoclaro.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.textoclaro.setFrame(True)
        self.textoclaro.setAlignment(QtCore.Qt.AlignCenter)
        self.textoclaro.setReadOnly(True)
        self.textoclaro.setObjectName("textoclaro")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.textoclaro)
        self.label = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.formLayout_11.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.formLayout_3)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setContentsMargins(20, 32, 0, -1)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_62 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_62.setObjectName("label_62")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.botonmezclar = QtWidgets.QPushButton(self.AlgoritmoMIBS1)
        self.botonmezclar.setEnabled(False)
        self.botonmezclar.setObjectName("botonmezclar")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.botonmezclar)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 5, 20, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_63 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_16.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_64.setEnabled(True)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_16.addWidget(self.label_64)
        self.trozo8_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo8_2.setText("")
        self.trozo8_2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo8_2.setObjectName("trozo8_2")
        self.horizontalLayout_16.addWidget(self.trozo8_2)
        self.label_65 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_65.setEnabled(True)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_16.addWidget(self.label_65)
        self.trozo7_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo7_2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo7_2.setObjectName("trozo7_2")
        self.horizontalLayout_16.addWidget(self.trozo7_2)
        self.label_66 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_66.setEnabled(True)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_16.addWidget(self.label_66)
        self.trozo6_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo6_2.setObjectName("trozo6_2")
        self.horizontalLayout_16.addWidget(self.trozo6_2)
        self.label_67 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_67.setEnabled(True)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_16.addWidget(self.label_67)
        self.trozo5_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo5_2.setObjectName("trozo5_2")
        self.horizontalLayout_16.addWidget(self.trozo5_2)
        self.label_68 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_68.setEnabled(True)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_16.addWidget(self.label_68)
        self.trozo4_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo4_2.setObjectName("trozo4_2")
        self.horizontalLayout_16.addWidget(self.trozo4_2)
        self.label_69 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_69.setEnabled(True)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_16.addWidget(self.label_69)
        self.trozo3_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo3_2.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.trozo3_2.setText("")
        self.trozo3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo3_2.setReadOnly(True)
        self.trozo3_2.setObjectName("trozo3_2")
        self.horizontalLayout_16.addWidget(self.trozo3_2)
        self.label_70 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_70.setEnabled(True)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_16.addWidget(self.label_70)
        self.trozo2_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo2_2.setObjectName("trozo2_2")
        self.horizontalLayout_16.addWidget(self.trozo2_2)
        self.label_71 = QtWidgets.QLabel(self.AlgoritmoMIBS1)
        self.label_71.setEnabled(True)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_16.addWidget(self.label_71)
        self.trozo1_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS1)
        self.trozo1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo1_2.setObjectName("trozo1_2")
        self.horizontalLayout_16.addWidget(self.trozo1_2)
        self.formLayout_6.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_16)
        self.formLayout_11.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.formLayout_6)
        AlgoritmoMIBS.addTab(self.AlgoritmoMIBS1, "")
        self.AlgoritmoMIBS2 = QtWidgets.QWidget()
        self.AlgoritmoMIBS2.setObjectName("AlgoritmoMIBS2")
        self.formLayout_13 = QtWidgets.QFormLayout(self.AlgoritmoMIBS2)
        self.formLayout_13.setContentsMargins(0, 0, 0, 0)
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_4 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_4.setObjectName("label_4")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_72 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_72.setObjectName("label_72")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_72)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.botonPermutar = QtWidgets.QPushButton(self.AlgoritmoMIBS2)
        self.botonPermutar.setEnabled(False)
        self.botonPermutar.setObjectName("botonPermutar")
        self.horizontalLayout_18.addWidget(self.botonPermutar)
        self.botonverPBox = QtWidgets.QPushButton(self.AlgoritmoMIBS2)
        self.botonverPBox.setObjectName("botonverPBox")
        self.horizontalLayout_18.addWidget(self.botonverPBox)
        self.formLayout_7.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 5, 20, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_73 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_17.addWidget(self.label_73)
        self.labely5 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.labely5.setEnabled(False)
        self.labely5.setObjectName("labely5")
        self.horizontalLayout_17.addWidget(self.labely5)
        self.trozo8_3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.trozo8_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo8_3.setObjectName("trozo8_3")
        self.horizontalLayout_17.addWidget(self.trozo8_3)
        self.labely4 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.labely4.setEnabled(False)
        self.labely4.setObjectName("labely4")
        self.horizontalLayout_17.addWidget(self.labely4)
        self.trozo7_3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.trozo7_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo7_3.setObjectName("trozo7_3")
        self.horizontalLayout_17.addWidget(self.trozo7_3)
        self.labely7 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.labely7.setEnabled(False)
        self.labely7.setObjectName("labely7")
        self.horizontalLayout_17.addWidget(self.labely7)
        self.trozo6_3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.trozo6_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo6_3.setObjectName("trozo6_3")
        self.horizontalLayout_17.addWidget(self.trozo6_3)
        self.labely6 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.labely6.setEnabled(False)
        self.labely6.setObjectName("labely6")
        self.horizontalLayout_17.addWidget(self.labely6)
        self.trozo5_3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.trozo5_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo5_3.setObjectName("trozo5_3")
        self.horizontalLayout_17.addWidget(self.trozo5_3)
        self.labely3 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.labely3.setEnabled(False)
        self.labely3.setObjectName("labely3")
        self.horizontalLayout_17.addWidget(self.labely3)
        self.trozo4_3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.trozo4_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo4_3.setObjectName("trozo4_3")
        self.horizontalLayout_17.addWidget(self.trozo4_3)
        self.labely1 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.labely1.setEnabled(False)
        self.labely1.setObjectName("labely1")
        self.horizontalLayout_17.addWidget(self.labely1)
        self.trozo3_3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.trozo3_3.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.trozo3_3.setText("")
        self.trozo3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo3_3.setReadOnly(True)
        self.trozo3_3.setObjectName("trozo3_3")
        self.horizontalLayout_17.addWidget(self.trozo3_3)
        self.labely8 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.labely8.setEnabled(False)
        self.labely8.setObjectName("labely8")
        self.horizontalLayout_17.addWidget(self.labely8)
        self.trozo2_3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.trozo2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo2_3.setObjectName("trozo2_3")
        self.horizontalLayout_17.addWidget(self.trozo2_3)
        self.labely2 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.labely2.setEnabled(False)
        self.labely2.setObjectName("labely2")
        self.horizontalLayout_17.addWidget(self.labely2)
        self.trozo1_3 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.trozo1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.trozo1_3.setObjectName("trozo1_3")
        self.horizontalLayout_17.addWidget(self.trozo1_3)
        self.formLayout_7.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_17)
        self.formLayout_13.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.formLayout_7)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setContentsMargins(20, 0, 0, -1)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_84 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_84.setObjectName("label_84")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_84)
        self.formLayout_13.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.formLayout_8)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setContentsMargins(20, 20, -1, -1)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_85 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_85.setObjectName("label_85")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_85)
        self.botonxor_2 = QtWidgets.QPushButton(self.AlgoritmoMIBS2)
        self.botonxor_2.setEnabled(False)
        self.botonxor_2.setObjectName("botonxor_2")
        self.formLayout_9.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.botonxor_2)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_77 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_13.addWidget(self.label_77)
        self.salida = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.salida.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.salida.setText("")
        self.salida.setAlignment(QtCore.Qt.AlignCenter)
        self.salida.setDragEnabled(False)
        self.salida.setReadOnly(True)
        self.salida.setObjectName("salida")
        self.horizontalLayout_13.addWidget(self.salida)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_79 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_14.addWidget(self.label_79)
        self.right = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.right.setFont(font)
        self.right.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.right.setText("")
        self.right.setFrame(True)
        self.right.setAlignment(QtCore.Qt.AlignCenter)
        self.right.setReadOnly(True)
        self.right.setObjectName("right")
        self.horizontalLayout_14.addWidget(self.right)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_14)
        self.formLayout_9.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_19)
        self.formLayout_13.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.formLayout_9)
        self.label_2 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_2.setObjectName("label_2")
        self.formLayout_13.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_83 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_83.setText("")
        self.label_83.setObjectName("label_83")
        self.formLayout_13.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.label_83)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(20, 0, 456, -1)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_80 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_21.addWidget(self.label_80)
        self.resultadoxor_2 = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.resultadoxor_2.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.resultadoxor_2.setText("")
        self.resultadoxor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.resultadoxor_2.setReadOnly(True)
        self.resultadoxor_2.setObjectName("resultadoxor_2")
        self.horizontalLayout_21.addWidget(self.resultadoxor_2)
        self.formLayout_13.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_21)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setContentsMargins(20, 30, 0, 23)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_18 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_18.setObjectName("label_18")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.botonsiguienteronda = QtWidgets.QPushButton(self.AlgoritmoMIBS2)
        self.botonsiguienteronda.setEnabled(False)
        self.botonsiguienteronda.setAutoDefault(False)
        self.botonsiguienteronda.setObjectName("botonsiguienteronda")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.botonsiguienteronda)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 5, 0, 13)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_24 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        self.lefti = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        self.lefti.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.lefti.setText("")
        self.lefti.setAlignment(QtCore.Qt.AlignCenter)
        self.lefti.setDragEnabled(False)
        self.lefti.setReadOnly(True)
        self.lefti.setObjectName("lefti")
        self.horizontalLayout_9.addWidget(self.lefti)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_81 = QtWidgets.QLabel(self.AlgoritmoMIBS2)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_10.addWidget(self.label_81)
        self.righti = QtWidgets.QLineEdit(self.AlgoritmoMIBS2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.righti.setFont(font)
        self.righti.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.righti.setText("")
        self.righti.setFrame(True)
        self.righti.setAlignment(QtCore.Qt.AlignCenter)
        self.righti.setReadOnly(True)
        self.righti.setObjectName("righti")
        self.horizontalLayout_10.addWidget(self.righti)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_10)
        self.formLayout_10.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_12)
        self.formLayout_13.setLayout(5, QtWidgets.QFormLayout.SpanningRole, self.formLayout_10)
        AlgoritmoMIBS.addTab(self.AlgoritmoMIBS2, "")
        self.actionCambiaTab = QtWidgets.QAction(AlgoritmoMIBS)
        self.actionCambiaTab.setObjectName("actionCambiaTab")

        self.retranslateUi(AlgoritmoMIBS)
        AlgoritmoMIBS.setCurrentIndex(1)
        self.botondividir.clicked['bool'].connect(self.label_17.clear)
        self.botondividir.clicked['bool'].connect(self.ronda.stepUp)
        self.ronda.valueChanged['int'].connect(self.label_42.setNum)
        QtCore.QMetaObject.connectSlotsByName(AlgoritmoMIBS)

    def retranslateUi(self, AlgoritmoMIBS):
        _translate = QtCore.QCoreApplication.translate
        AlgoritmoMIBS.setWindowTitle(_translate("AlgoritmoMIBS", "TabWidget"))
        self.label_3.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600;\">Algoritmo MIBS</span></p></body></html>"))
        self.label_43.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>Ronda </p></body></html>"))
        self.label_47.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600;\">Función F de Red Feistel: </span></p></body></html>"))
        self.label_17.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>Antes de comenzar las rondas, se divide el bloque inicial en dos bloques de 32 bits</p></body></html>"))
        self.label_23.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">i-1</span>: </p></body></html>"))
        self.leftinicial.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-style:normal;\">bloque left</span></p></body></html>"))
        self.label_40.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>R<span style=\" vertical-align:sub;\">i-1</span>: </p></body></html>"))
        self.rightinicial.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-style:normal;\">Bloque right</span></p></body></html>"))
        self.botondividir.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p>Dividir bloque de 64 bits</p></body></html>"))
        self.botondividir.setText(_translate("AlgoritmoMIBS", "Dividir"))
        self.label_41.setText(_translate("AlgoritmoMIBS", "i = "))
        self.label_42.setText(_translate("AlgoritmoMIBS", "Número de ronda"))
        self.label_44.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600;\">1. Adición de clave.</span> El nuevo estado (state<span style=\" vertical-align:sub;\">i</span>) será el resultado de una operación XOR entre L<span style=\" vertical-align:sub;\">i-1</span>, qué es la entrada de la función F, y <br/>&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;la clave de ronda i (obtenida en el paso 4 del cifrado didáctico).</p></body></html>"))
        self.botonxor.setText(_translate("AlgoritmoMIBS", "XOR"))
        self.label_48.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">i-1</span>: </p></body></html>"))
        self.left.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-style:normal;\">bloque left</span></p></body></html>"))
        self.label_50.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>K<span style=\" vertical-align:sub;\">i</span>:</p></body></html>"))
        self.claveronda.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-style:normal;\">Bloque right</span></p></body></html>"))
        self.label_51.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i </span>= </p></body></html>"))
        self.botonTrozear.setText(_translate("AlgoritmoMIBS", "Trozear"))
        self.botontransformar.setText(_translate("AlgoritmoMIBS", "Transformar por SBox"))
        self.botonverSBox.setText(_translate("AlgoritmoMIBS", "Ver SBox"))
        self.label_61.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600;\">2. Capa de sustitución.</span> Se trozea state<span style=\" vertical-align:sub;\">i </span>en 8 trozos. Cada trozo pasa por la SBox (caja de sustitución) y se obtienen nuevos valores.</p></body></html>"))
        self.label_52.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>Trozos: </p></body></html>"))
        self.label_53.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">8:</span></p></body></html>"))
        self.label_54.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">7</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_55.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">6</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_56.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">5</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_57.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">4</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_58.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">3</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_59.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">2</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_60.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">1</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.textoclaro.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p>Bloque a cifrar</p></body></html>"))
        self.textoclaro.setText(_translate("AlgoritmoMIBS", "0100010101101110001000000111010101101110001000000110110001110101"))
        self.label.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Nota</span>: Cifraremos el bloque 0 del ejemplo.</p></body></html>"))
        self.label_62.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600;\">3. Capa de mezcla.</span> Se obtienen nuevos trozos como resultado de operaciones XOR entre los trozos obtenidos en el paso 2.</p></body></html>"))
        self.botonmezclar.setText(_translate("AlgoritmoMIBS", "Mezclar"))
        self.label_63.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>Trozos: </p></body></html>"))
        self.label_64.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">8\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_65.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">7</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_66.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">6</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_67.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">5</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_68.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">4</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_69.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">3</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_70.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">2</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_71.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">1</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        AlgoritmoMIBS.setTabText(AlgoritmoMIBS.indexOf(self.AlgoritmoMIBS1), _translate("AlgoritmoMIBS", "Algoritmo MIBS (1)"))
        self.label_4.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Algoritmo MIBS</span></p></body></html>"))
        self.label_72.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600;\">4. Capa de permutación.</span> Los ocho trozos de salida de la capa de mezcla , se permutan según la PBox (caja de permutación).</p></body></html>"))
        self.botonPermutar.setText(_translate("AlgoritmoMIBS", "Permutar"))
        self.botonverPBox.setText(_translate("AlgoritmoMIBS", "Ver PBox"))
        self.label_73.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>Trozos: </p></body></html>"))
        self.labely5.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">5</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.labely4.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">4</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.labely7.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">7</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.labely6.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">6</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.labely3.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">3</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.labely1.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">1</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.labely8.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">8</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.labely2.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-size:12pt;\">y</span><span style=\" font-size:12pt; vertical-align:sub;\">2</span><span style=\" font-size:12pt; vertical-align:sub;\">\'</span><span style=\" font-size:12pt;\">:</span></p></body></html>"))
        self.label_84.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>Anidamos los trozos y obtenemos la salida de la funcion F.</p></body></html>"))
        self.label_85.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600;\">5. Obtención nuevo bloque de ronda L</span><span style=\" font-weight:600; vertical-align:sub;\">i</span><span style=\" font-weight:600;\">.</span> Se realiza una operación XOR entre la salida de F y el bloque R<span style=\" vertical-align:sub;\">i-1. </span></p><p>El resultado será el nuevo bloque L<span style=\" vertical-align:sub;\">i.</span></p></body></html>"))
        self.botonxor_2.setText(_translate("AlgoritmoMIBS", "XOR"))
        self.label_77.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>salida F:</p></body></html>"))
        self.salida.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-style:normal;\">bloque left</span></p></body></html>"))
        self.label_79.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>R<span style=\" vertical-align:sub;\">i-1</span>:</p></body></html>"))
        self.right.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-style:normal;\">Bloque right</span></p></body></html>"))
        self.label_2.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-weight:600;\">   Cuando se llega a la última ronda (i = 32) se anidan Li y Ri y se obtiene el bloque 0 cifrado.</span></p></body></html>"))
        self.label_80.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">i</span> : </p></body></html>"))
        self.label_18.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>El bloque right R<span style=\" vertical-align:sub;\">i</span>, será el bloque L<span style=\" vertical-align:sub;\">i-1</span>.</p><p>Por tanto, los dos<span style=\" font-weight:600;\"> nuevos bloques de ronda</span> son:</p></body></html>"))
        self.botonsiguienteronda.setText(_translate("AlgoritmoMIBS", "Siguiente ronda"))
        self.label_24.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>L<span style=\" vertical-align:sub;\">i</span>: </p></body></html>"))
        self.lefti.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-style:normal;\">bloque left</span></p></body></html>"))
        self.label_81.setText(_translate("AlgoritmoMIBS", "<html><head/><body><p>R<span style=\" vertical-align:sub;\">i</span>: </p></body></html>"))
        self.righti.setToolTip(_translate("AlgoritmoMIBS", "<html><head/><body><p><span style=\" font-style:normal;\">Bloque right</span></p></body></html>"))
        AlgoritmoMIBS.setTabText(AlgoritmoMIBS.indexOf(self.AlgoritmoMIBS2), _translate("AlgoritmoMIBS", "Algoritmo MIBS (2)"))
        self.actionCambiaTab.setText(_translate("AlgoritmoMIBS", "CambiaPestaña"))
        self.actionCambiaTab.setToolTip(_translate("AlgoritmoMIBS", "Siguiente ronda"))

