# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'obtencionclavesMIBS.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_procesoSubclaves(object):
    def setupUi(self, procesoSubclaves):
        procesoSubclaves.setObjectName("procesoSubclaves")
        procesoSubclaves.resize(933, 764)
        procesoSubclaves.setLayoutDirection(QtCore.Qt.LeftToRight)
        procesoSubclaves.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.centralwidget = QtWidgets.QWidget(procesoSubclaves)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.ronda = QtWidgets.QSpinBox(self.centralwidget)
        self.ronda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ronda.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ronda.setReadOnly(True)
        self.ronda.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ronda.setMinimum(0)
        self.ronda.setMaximum(32)
        self.ronda.setProperty("value", 0)
        self.ronda.setObjectName("ronda")
        self.horizontalLayout_3.addWidget(self.ronda)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.botonrotar = QtWidgets.QPushButton(self.centralwidget)
        self.botonrotar.setObjectName("botonrotar")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.botonrotar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botonsbox = QtWidgets.QPushButton(self.centralwidget)
        self.botonsbox.setEnabled(False)
        self.botonsbox.setObjectName("botonsbox")
        self.horizontalLayout_2.addWidget(self.botonsbox)
        self.botonverSBox2 = QtWidgets.QPushButton(self.centralwidget)
        self.botonverSBox2.setObjectName("botonverSBox2")
        self.horizontalLayout_2.addWidget(self.botonverSBox2)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.botonxor = QtWidgets.QPushButton(self.centralwidget)
        self.botonxor.setEnabled(False)
        self.botonxor.setObjectName("botonxor")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.botonxor)
        self.botonsubclave = QtWidgets.QPushButton(self.centralwidget)
        self.botonsubclave.setEnabled(False)
        self.botonsubclave.setObjectName("botonsubclave")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.botonsubclave)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.textoclaveinicial = QtWidgets.QLineEdit(self.centralwidget)
        self.textoclaveinicial.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textoclaveinicial.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.textoclaveinicial.setReadOnly(True)
        self.textoclaveinicial.setObjectName("textoclaveinicial")
        self.horizontalLayout.addWidget(self.textoclaveinicial)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setSpacing(0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.textorota = QtWidgets.QLineEdit(self.centralwidget)
        self.textorota.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textorota.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.textorota.setText("")
        self.textorota.setReadOnly(True)
        self.textorota.setObjectName("textorota")
        self.horizontalLayout_6.addWidget(self.textorota)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(-1, 20, -1, -1)
        self.formLayout_3.setSpacing(0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.textosbox = QtWidgets.QLineEdit(self.centralwidget)
        self.textosbox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textosbox.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.textosbox.setText("")
        self.textosbox.setReadOnly(True)
        self.textosbox.setObjectName("textosbox")
        self.horizontalLayout_8.addWidget(self.textosbox)
        self.formLayout_3.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.formLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setContentsMargins(-1, 20, -1, -1)
        self.formLayout_4.setSpacing(0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.textoxor = QtWidgets.QLineEdit(self.centralwidget)
        self.textoxor.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textoxor.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.textoxor.setText("")
        self.textoxor.setReadOnly(True)
        self.textoxor.setObjectName("textoxor")
        self.horizontalLayout_9.addWidget(self.textoxor)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_9)
        self.formLayout.setLayout(8, QtWidgets.QFormLayout.SpanningRole, self.formLayout_4)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setContentsMargins(-1, 20, -1, -1)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.textoclave = QtWidgets.QLineEdit(self.centralwidget)
        self.textoclave.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textoclave.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.textoclave.setText("")
        self.textoclave.setReadOnly(True)
        self.textoclave.setObjectName("textoclave")
        self.horizontalLayout_10.addWidget(self.textoclave)
        self.formLayout_5.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_10)
        self.formLayout.setLayout(10, QtWidgets.QFormLayout.SpanningRole, self.formLayout_5)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setSpacing(0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.textEdit)
        self.formLayout.setLayout(12, QtWidgets.QFormLayout.SpanningRole, self.formLayout_6)
        procesoSubclaves.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(procesoSubclaves)
        self.statusbar.setObjectName("statusbar")
        procesoSubclaves.setStatusBar(self.statusbar)

        self.retranslateUi(procesoSubclaves)
        self.botonrotar.clicked['bool'].connect(self.ronda.stepUp)
        QtCore.QMetaObject.connectSlotsByName(procesoSubclaves)

    def retranslateUi(self, procesoSubclaves):
        _translate = QtCore.QCoreApplication.translate
        procesoSubclaves.setWindowTitle(_translate("procesoSubclaves", "Algoritmo de obtención claves MIBS"))
        self.label_3.setText(_translate("procesoSubclaves", "<html><head/><body><p><span style=\" font-weight:600;\">Algoritmo de generación de claves</span></p></body></html>"))
        self.label.setText(_translate("procesoSubclaves", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Nota</span>: El estado inicial equivale a la clave (en binario) introducida por el usuario.</p></body></html>"))
        self.label_5.setText(_translate("procesoSubclaves", "<html><head/><body><p><span style=\" font-weight:600;\">Ronda </span></p></body></html>"))
        self.botonrotar.setText(_translate("procesoSubclaves", "Rotar"))
        self.botonsbox.setText(_translate("procesoSubclaves", "SBox"))
        self.botonverSBox2.setText(_translate("procesoSubclaves", "Ver SBox"))
        self.botonxor.setText(_translate("procesoSubclaves", "XOR"))
        self.botonsubclave.setText(_translate("procesoSubclaves", "obtener subclave"))
        self.label_2.setText(_translate("procesoSubclaves", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i: </span></p></body></html>"))
        self.textoclaveinicial.setText(_translate("procesoSubclaves", "0110001101101001011001100111001001001101010010010100001001010011"))
        self.label_9.setText(_translate("procesoSubclaves", "<html><head/><body><p>1. state<span style=\" vertical-align:super;\">i </span>se rota 15 bits a la derecha.<br/></p></body></html>"))
        self.label_8.setText(_translate("procesoSubclaves", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i</span>:<span style=\" vertical-align:super;\"/></p></body></html>"))
        self.label_11.setText(_translate("procesoSubclaves", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i</span>:<span style=\" vertical-align:super;\"/></p></body></html>"))
        self.label_12.setText(_translate("procesoSubclaves", "<html><head/><body><p>2. Los 4 bits más a la izquierda de state<span style=\" vertical-align:super;\">i </span>se transforman a través de la SBox. El resto no varía.<br/></p></body></html>"))
        self.label_14.setText(_translate("procesoSubclaves", "<html><head/><body><p>3. Se realiza una operación XOR entre los bits de state<span style=\" vertical-align:super;\">i </span>, situados entre la posición 15 a la 11, y el contador de ronda.<br/></p></body></html>"))
        self.label_13.setText(_translate("procesoSubclaves", "<html><head/><body><p>state<span style=\" vertical-align:super;\">i</span>:<span style=\" vertical-align:super;\"/></p></body></html>"))
        self.label_16.setText(_translate("procesoSubclaves", "<html><head/><body><p>4. La clave de ronda serán los 32 bits más a la izquierda del state<span style=\" vertical-align:super;\">i </span><br/></p></body></html>"))
        self.label_15.setText(_translate("procesoSubclaves", "<html><head/><body><p>clave<span style=\" vertical-align:super;\">i</span>:<span style=\" vertical-align:super;\"/></p></body></html>"))
        self.label_17.setText(_translate("procesoSubclaves", "<html><head/><body><p><span style=\" font-weight:600;\">Claves de ronda:</span></p></body></html>"))

