# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MIBSdidáctico_2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_segunda(object):
    def setupUi(self, segunda):
        segunda.setObjectName("segunda")
        segunda.resize(883, 609)
        segunda.setLayoutDirection(QtCore.Qt.LeftToRight)
        segunda.setAutoFillBackground(False)
        segunda.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(segunda)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botonconvertir = QtWidgets.QPushButton(self.centralwidget)
        self.botonconvertir.setObjectName("botonconvertir")
        self.horizontalLayout.addWidget(self.botonconvertir)
        self.textoclave = QtWidgets.QLineEdit(self.centralwidget)
        self.textoclave.setStyleSheet("font: italic 11pt \"Ubuntu\";")
        self.textoclave.setReadOnly(True)
        self.textoclave.setObjectName("textoclave")
        self.horizontalLayout.addWidget(self.textoclave)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.texto = QtWidgets.QTextEdit(self.centralwidget)
        self.texto.setReadOnly(True)
        self.texto.setObjectName("texto")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.texto)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botonGeneraSubclaves = QtWidgets.QPushButton(self.centralwidget)
        self.botonGeneraSubclaves.setStyleSheet("")
        self.botonGeneraSubclaves.setIconSize(QtCore.QSize(16, 16))
        self.botonGeneraSubclaves.setCheckable(False)
        self.botonGeneraSubclaves.setObjectName("botonGeneraSubclaves")
        self.horizontalLayout_2.addWidget(self.botonGeneraSubclaves)
        self.botonverproceso = QtWidgets.QPushButton(self.centralwidget)
        self.botonverproceso.setObjectName("botonverproceso")
        self.horizontalLayout_2.addWidget(self.botonverproceso)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.formLayout_4.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.texto_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.texto_2.setReadOnly(True)
        self.texto_2.setObjectName("texto_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.texto_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.botoncifrarbloques = QtWidgets.QPushButton(self.centralwidget)
        self.botoncifrarbloques.setStyleSheet("")
        self.botoncifrarbloques.setIconSize(QtCore.QSize(16, 16))
        self.botoncifrarbloques.setCheckable(False)
        self.botoncifrarbloques.setObjectName("botoncifrarbloques")
        self.horizontalLayout_3.addWidget(self.botoncifrarbloques)
        self.botonverproceso_2 = QtWidgets.QPushButton(self.centralwidget)
        self.botonverproceso_2.setObjectName("botonverproceso_2")
        self.horizontalLayout_3.addWidget(self.botonverproceso_2)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.formLayout_4.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.texto_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.texto_3.setReadOnly(True)
        self.texto_3.setObjectName("texto_3")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.texto_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.botontextocifrado = QtWidgets.QPushButton(self.centralwidget)
        self.botontextocifrado.setStyleSheet("")
        self.botontextocifrado.setIconSize(QtCore.QSize(16, 16))
        self.botontextocifrado.setCheckable(False)
        self.botontextocifrado.setObjectName("botontextocifrado")
        self.horizontalLayout_4.addWidget(self.botontextocifrado)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.formLayout_4.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.formLayout_3)
        segunda.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(segunda)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 25))
        self.menubar.setObjectName("menubar")
        segunda.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(segunda)
        self.statusbar.setObjectName("statusbar")
        segunda.setStatusBar(self.statusbar)

        self.retranslateUi(segunda)
        QtCore.QMetaObject.connectSlotsByName(segunda)

    def retranslateUi(self, segunda):
        _translate = QtCore.QCoreApplication.translate
        segunda.setWindowTitle(_translate("segunda", "MIBS didáctico"))
        self.label.setText(_translate("segunda", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Cifrado de bloques MIBS</span></p></body></html>"))
        self.label_4.setText(_translate("segunda", "3. Se convierte la clave inicial de ASCII a binario: "))
        self.botonconvertir.setText(_translate("segunda", "Convertir clave"))
        self.textoclave.setText(_translate("segunda", "cifrMIBS"))
        self.texto.setHtml(_translate("segunda", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.botonGeneraSubclaves.setText(_translate("segunda", "Generar subclaves"))
        self.botonverproceso.setText(_translate("segunda", "Ver proceso"))
        self.label_3.setText(_translate("segunda", "<html><head/><body><p>4. A partir de la clave inicial, se generan las claves de 32 bits necesarias para cada ronda de cifrado.</p></body></html>"))
        self.texto_2.setHtml(_translate("segunda", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.botoncifrarbloques.setText(_translate("segunda", "Cifrar bloques"))
        self.botonverproceso_2.setText(_translate("segunda", "Ver proceso"))
        self.label_5.setText(_translate("segunda", "<html><head/><body><p>5. Se cifraran 152 bloques. Para cada bloque se realiza el cifrado MIBS de 32 rondas con las subclaves de ronda generada en el paso 4.</p><p><span style=\" font-weight:600; text-decoration: underline;\">Nota:</span> Los bloques cifrados se muestran en hexadecimal.</p></body></html>"))
        self.label_6.setText(_translate("segunda", "<html><head/><body><p>6. Una vez cifrados los 152 bloques, se anidan en orden ascendente en el que han sido cifrados, y obtenemos el texto cifrado.</p></body></html>"))
        self.texto_3.setHtml(_translate("segunda", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.botontextocifrado.setText(_translate("segunda", "Texto cifrado"))

